//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlsunView.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmInformation
    {
        public int ID { get; set; }
        public Nullable<int> DID { get; set; }
        public string DName { get; set; }
        public string DAddress { get; set; }
        public Nullable<short> AISlot { get; set; }
        public string AIType { get; set; }
        public string AILevel { get; set; }
        public string AIContent { get; set; }
        public Nullable<System.DateTime> AITime { get; set; }
        public Nullable<bool> AIConfirm { get; set; }
        public Nullable<System.DateTime> AIConfirmTime { get; set; }
        public Nullable<int> UID { get; set; }
        public string ULoginName { get; set; }
        public string UName { get; set; }
    }
}
