//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlsunView.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceOperationLog
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public string ULoginName { get; set; }
        public string UName { get; set; }
        public string DOLOperationType { get; set; }
        public string DOLOperationDetials { get; set; }
        public string DOLOperationResult { get; set; }
        public Nullable<System.DateTime> DOLOperationTime { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SID { get; set; }
        public string SName { get; set; }
        public string SAddress { get; set; }
        public Nullable<int> DID { get; set; }
        public string DName { get; set; }
        public string DAddress { get; set; }
        public Nullable<short> DOLDeviceSlot { get; set; }
        public string DOLCardSN { get; set; }
        public string DOLCardType { get; set; }
    }
}
