//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlsunView.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int ID { get; set; }
        public Nullable<int> SID { get; set; }
        public string DName { get; set; }
        public string DAddress { get; set; }
        public string DIcon { get; set; }
        public string DType { get; set; }
        public string DProtocal { get; set; }
        public Nullable<int> CoordinateX { get; set; }
        public Nullable<int> CoordinateY { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> EditorID { get; set; }
        public Nullable<System.DateTime> EditingTime { get; set; }
        public Nullable<int> DPort { get; set; }
    
        public virtual Subnet Subnet { get; set; }
    }
}
