//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlsunView.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GlsunViewEntities : DbContext
    {
        public GlsunViewEntities()
            : base("name=GlsunViewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authority> Authority { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<ModuleAuthority> ModuleAuthority { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<v_ModuleUser> v_ModuleUser { get; set; }
        public virtual DbSet<v_ModuleTree> v_ModuleTree { get; set; }
        public virtual DbSet<v_User> v_User { get; set; }
        public virtual DbSet<v_Role> v_Role { get; set; }
        public virtual DbSet<v_ModuleAuthority> v_ModuleAuthority { get; set; }
        public virtual DbSet<v_UserRole> v_UserRole { get; set; }
        public virtual DbSet<RoleAuthority> RoleAuthority { get; set; }
        public virtual DbSet<v_Authority> v_Authority { get; set; }
        public virtual DbSet<v_UserModule> v_UserModule { get; set; }
        public virtual DbSet<v_UserModuleAuthority> v_UserModuleAuthority { get; set; }
        public virtual DbSet<UserLog> UserLog { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<DeviceLine> DeviceLine { get; set; }
        public virtual DbSet<Subnet> Subnet { get; set; }
        public virtual DbSet<SubnetLine> SubnetLine { get; set; }
        public virtual DbSet<SceneLocation> SceneLocation { get; set; }
        public virtual DbSet<DeviceOperationLog> DeviceOperationLog { get; set; }
        public virtual DbSet<TopologyOperationLog> TopologyOperationLog { get; set; }
        public virtual DbSet<AlarmInformation> AlarmInformation { get; set; }
        public virtual DbSet<v_AlarmInfo> v_AlarmInfo { get; set; }
        public virtual DbSet<v_LastestWeekAlarmStatistics> v_LastestWeekAlarmStatistics { get; set; }
        public virtual DbSet<v_MachineRoom> v_MachineRoom { get; set; }
        public virtual DbSet<v_MachineShelf> v_MachineShelf { get; set; }
        public virtual DbSet<MachineFrame> MachineFrame { get; set; }
        public virtual DbSet<MachineRoom> MachineRoom { get; set; }
        public virtual DbSet<MachineShelf> MachineShelf { get; set; }
        public virtual DbSet<v_MachineFrame> v_MachineFrame { get; set; }
    
        [DbFunction("GlsunViewEntities", "F_GetTreeModuleID")]
        public virtual IQueryable<Nullable<int>> F_GetTreeModuleID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<int>>("[GlsunViewEntities].[F_GetTreeModuleID]()");
        }
    }
}
