//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlsunView.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpticalCable
    {
        public int ID { get; set; }
        public string OC_Name { get; set; }
        public Nullable<int> OC_MarkIDA { get; set; }
        public Nullable<int> OC_MarkIDB { get; set; }
        public Nullable<decimal> OC_MarkRetainA { get; set; }
        public Nullable<decimal> OC_MarkRetainB { get; set; }
        public Nullable<decimal> OC_Length { get; set; }
        public Nullable<decimal> OC_TotalLength { get; set; }
        public Nullable<int> OC_FiberCount { get; set; }
        public string OC_Nodes { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> EditorID { get; set; }
        public Nullable<System.DateTime> EditingTime { get; set; }
    }
}
