//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlsunView.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int ID { get; set; }
        public Nullable<int> ULOperatorID { get; set; }
        public string ULOperator { get; set; }
        public string ULOperationType { get; set; }
        public string ULOperationDetials { get; set; }
        public string ULOperationResult { get; set; }
        public Nullable<System.DateTime> ULOperationTime { get; set; }
        public Nullable<int> UID { get; set; }
        public string ULoginName { get; set; }
        public string UName { get; set; }
        public string ULRemark { get; set; }
    
        public virtual User User { get; set; }
    }
}
