//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlsunView.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_MachineShelf
    {
        public int ID { get; set; }
        public string MSName { get; set; }
        public string MSNumber { get; set; }
        public Nullable<short> MSLayers { get; set; }
        public string MSIcon { get; set; }
        public Nullable<int> MRID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> EditorID { get; set; }
        public Nullable<System.DateTime> EditingTime { get; set; }
        public string MRName { get; set; }
        public string Creator { get; set; }
        public string Editor { get; set; }
    }
}
