//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlsunView.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_UserRole
    {
        public long ROW_ID { get; set; }
        public int UID { get; set; }
        public string ULoginName { get; set; }
        public string UName { get; set; }
        public Nullable<int> RID { get; set; }
        public string RName { get; set; }
    }
}
