//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlsunView.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_UserModuleAuthority
    {
        public long V_ID { get; set; }
        public int UID { get; set; }
        public string UName { get; set; }
        public Nullable<int> MID { get; set; }
        public Nullable<int> MPID { get; set; }
        public string MName { get; set; }
        public string MUrl { get; set; }
        public Nullable<int> ID { get; set; }
        public string AName { get; set; }
        public string ACode { get; set; }
        public string AType { get; set; }
        public string AIcon { get; set; }
        public string AIconType { get; set; }
        public string AClassName { get; set; }
        public Nullable<short> AShowNumber { get; set; }
        public Nullable<bool> AIsCommon { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> EditorID { get; set; }
        public Nullable<System.DateTime> EditingTime { get; set; }
    }
}
